// Local
@url =http://127.0.0.1:3333/api/v1

// HML
//@url =http://127.0.0.1:3333/api/v1

// Prod
//@url =https://maestro-frotas-backend-my.herokuapp.com/api/v1

@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkZXNjcmlwdGlvbiI6IkpXVCBUb2tlbiIsImlkIjoxLCJ0eXBlIjoicm9vdCIsInVzZXIiOnsiaWQiOjEsIm5vbWUiOiJSYWZhZWwiLCJzb2JyZW5vbWUiOiJBLiBSYWJlbG8iLCJlbWFpbCI6InJhZmFlbF9yYWJlbG9AbGl2ZS5jb20iLCJjcGYiOiIwNzkxOTA0ODY1NiIsImRhdGFfbmFzY2ltZW50byI6IjE5ODUtMDUtMjBUMDM6MDA6MDAuMDAwWiIsInJvbGVfbmFtZSI6InJvb3QiLCJhY3RpdmVfcm9sZSI6MSwiaXNfcm9vdCI6MSwiaXNfc3lzIjowLCJpc191c2VyIjoxLCJpc19hZG0iOjAsInR5cGUiOiJyb290In0sImlhdCI6MTYxOTE0NTQ0NywiZXhwIjoxNjE5MTUxODQ3fQ.fULokNq59P0uOaB78XkEqzlAoCjzxAgMrUEiSLD5FvA

GET {{url}}/
content-type: application/json
client_ip: 192.168.0.1
###

// user/
GET {{url}}/user
content-type: application/json
Authorization: Bearer {{token}}
###
GET {{url}}/user/todos
content-type: application/json
Authorization: Bearer {{token}}
###
GET {{url}}/user/1
content-type: application/json
Authorization: Bearer {{token}}
###

POST {{url}}/user/register
content-type: application/json
Authorization: Bearer {{token}}

{
    "nome": "Rafael",
    "cpf": "968.513.190-20",
    "email": "ra@gmail.com",
    "senha": "123ad123"
}
###
PUT {{url}}/user/5fc28d6ce11978245992e085
content-type: application/json
Authorization: Bearer {{token}}

{
    "nome": "Teste R&R UPDATED",
    "sobrenome": "Tester",
    "data_nascimento": "1986-08-10"
}
###
PUT {{url}}/user
content-type: application/json
Authorization: Bearer {{token}}

{
    "nome": "System",
    "sobrenome": "Tester",
    "data_nascimento": "1986-08-10"
}
###
DELETE {{url}}/user/5fc28d6ce11978245992e085
content-type: application/json
Authorization: Bearer {{token}}
###

// login
POST  {{url}}/auth/login
content-type: application/json
client_ip: 192.168.0.1

{
    //"cpf": "{{adm_user}}",
    "cpf": "07919048656",
    "senha": "123adg666"
}
###

POST  {{url}}/auth/recovery/send-info
content-type: application/json
client_ip: 192.168.0.1

{
    "cpf": "07919048656"
}
###

POST  {{url}}/auth/recovery/validate-code
content-type: application/json
client_ip: 192.168.0.1

{
    "cpf": "079.19048656",
    "code": "558189"
}
###

POST  {{url}}/auth/recovery/set-password
content-type: application/json
client_ip: 192.168.0.1

{
    "cpf": "07919048656",
    "code": "983347",
    "pass": "123adg666"
}
###

// Message
POST  {{url}}/message/contactpage
content-type: application/json
Authorization: Bearer {{token}}

{
    "name":"Rafael",
    "email":"rafael@email.com",
    "subject":"teste",
     "message":"no message inside"
}