// Local
@url =http://127.0.0.1:3333/api/v1

// HML
//@url =http://127.0.0.1:3333/api/v1

// Prod
//@url =https://maestro-frotas-backend-my.herokuapp.com/api/v1

@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkZXNjcmlwdGlvbiI6IkpXVCBUb2tlbiIsImlkIjoxLCJ0eXBlIjoiYWRtaW4iLCJ1c2VyIjp7ImlkIjoxLCJub21lIjoiUmFmYWVsIiwic29icmVub21lIjoiQS4gUmFiZWxvIiwiZW1haWwiOiJyYWZhZWxfcmFiZWxvQGxpdmUuY29tIiwiY3BmIjoiMDc5MTkwNDg2NTYiLCJkYXRhX25hc2NpbWVudG8iOiIxOTg1LTA1LTIwVDAzOjAwOjAwLjAwMFoiLCJyb2xlX25hbWUiOiJhZG0iLCJhY3RpdmVfcm9sZSI6MSwiaXNfcm9vdCI6MCwiaXNfc3lzIjowLCJpc191c2VyIjoxLCJpc19hZG0iOjEsInR5cGUiOiJhZG1pbiJ9LCJpYXQiOjE2MTgwMTU2ODEsImV4cCI6MTYxODAyMjA4MX0.hi6YdTS7q45CixLJLvUCKZl8C43wp5raIwu5N66Fq1w

GET {{url}}/
content-type: application/json
###

// user/
GET {{url}}/user
content-type: application/json
Authorization: Bearer {{token}}
###
GET {{url}}/user/todos
content-type: application/json
Authorization: Bearer {{token}}
###
GET {{url}}/user/1
content-type: application/json
Authorization: Bearer {{token}}
###

POST {{url}}/user/register
content-type: application/json
Authorization: Bearer {{token}}

{
    "nome": "Rafael",
    "cpf": "968.513.190-20",
    "email": "ra@gmail.com",
    "senha": "123ad123"
}
###
PUT {{url}}/user/5fc28d6ce11978245992e085
content-type: application/json
Authorization: Bearer {{token}}

{
    "nome": "Teste R&R UPDATED",
    "sobrenome": "Tester",
    "data_nascimento": "1986-08-10"
}
###
PUT {{url}}/user
content-type: application/json
Authorization: Bearer {{token}}

{
    "nome": "System",
    "sobrenome": "Tester",
    "data_nascimento": "1986-08-10"
}
###
DELETE {{url}}/user/5fc28d6ce11978245992e085
content-type: application/json
Authorization: Bearer {{token}}
###

// login
POST  {{url}}/auth/login
content-type: application/json

{
    //"cpf": "{{adm_user}}",
    "cpf": "07919048656",
    "senha": "123adg666"
}
###

POST  {{url}}/auth/recovery/send-info
content-type: application/json

{
    "cpf": "07919048656"
}
###

POST  {{url}}/auth/recovery/validate-code
content-type: application/json

{
    "cpf": "079.19048656",
    "code": "558189"
}
###

POST  {{url}}/auth/recovery/set-password
content-type: application/json

{
    "cpf": "07919048656",
    "code": "983347",
    "pass": "123adg666"
}
###