// Local
@userteste_cpf =580.306.610-96
@userteste_nome =tester
@userteste_email =tester@gmail.com
@userteste_senha =yanIx080)lK$c02
@url =http://127.0.0.1:3333/api/v1

// HML
//@url =http://127.0.0.1:3333/api/v1

// Prod
//@url =https://maestro-frotas-backend-my.herokuapp.com/api/v1

@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkZXNjcmlwdGlvbiI6IkpXVCBUb2tlbiIsImlkIjo1LCJ0eXBlIjoidXNlciIsInVzZXIiOnsiaWQiOjUsIm5vbWUiOiJ0ZXN0ZXIiLCJzb2JyZW5vbWUiOiIiLCJlbWFpbCI6Int7e3t1c2VydGVzdGVfZW1haWx9fSIsImNwZiI6IjU4MDMwNjYxMDk2IiwiZGF0YV9uYXNjaW1lbnRvIjpudWxsLCJyb2xlX25hbWUiOiJ1c2VyIiwiYWN0aXZlX3JvbGUiOjEsImlzX3Jvb3QiOjAsImlzX3N5cyI6MCwiaXNfdXNlciI6MSwiaXNfYWRtIjowLCJ0eXBlIjoidXNlciJ9LCJpYXQiOjE2MjEzOTAxNjIsImV4cCI6MTYyMTM5NjU2Mn0.PDGLCzQ8OxTny0w4aGmy-TOE1YnPW3saeyYitKM_Wvk

// info
GET {{url}}/
content-type: application/json
client_ip: 192.168.0.1
###

// user/
GET {{url}}/user/todos
content-type: application/json
Authorization: Bearer {{token}}
###

GET {{url}}/user/1
content-type: application/json
Authorization: Bearer {{token}}
###

POST {{url}}/user/register
content-type: application/json
Authorization: Bearer {{token}}
client_ip: 192.168.0.1

{
    "cpf": "{{userteste_cpf}}",
    "nome": "{{userteste_nome}}",
    "email": "{{userteste_email}}",
    "senha": "{{userteste_senha}}"
}
###

PUT {{url}}/user/5
content-type: application/json
Authorization: Bearer {{token}}

{
    "nome": "{{userteste_nome}}",
    "sobrenome": "Tester",
    "data_nascimento": "1986-08-10"
}
###

DELETE {{url}}/user/1
content-type: application/json
Authorization: Bearer {{token}}
###

// self
GET {{url}}/user
content-type: application/json
Authorization: Bearer {{token}}
###

PUT {{url}}/user
content-type: application/json
Authorization: Bearer {{token}}

{
    "nome": "{{userteste_nome}}",
    "sobrenome": "Tester",
    "data_nascimento": "1986-08-10"
}
###

// auth
POST  {{url}}/auth/login
content-type: application/json
client_ip: 192.168.0.1

{
    "cpf": "{{userteste_cpf}}",
    "senha": "{{userteste_senha}}"
}
###

POST  {{url}}/auth/recovery/send-info
content-type: application/json
client_ip: 192.168.0.1

{
    "cpf": "{{userteste_cpf}}"
}
###

POST  {{url}}/auth/recovery/validate-code
content-type: application/json
client_ip: 192.168.0.1

{
    "cpf": "{{userteste_cpf}}",
    "code": "870133"
}
###

POST  {{url}}/auth/recovery/set-password
content-type: application/json
client_ip: 192.168.0.1

{
    "cpf": "{{userteste_cpf}}",
    "code": "870133",
    "pass": "123adg666"
}
###